---
driver_plugin: zcloudjp
driver_config:
  api_key: <%= ENV['ZCLOUD_APIKEY']  %>
  ssh_key: <%= ENV['ZCLOUD_SSHKEY_PATH']  %>
  user: root

platforms:
- name: sm-base64
  driver_config:
    dataset: "sdc:sdc:base64:13.1.0"
    package: Small_1GB
    require_chef_omnibus: false
    with_gcc: true
  busser:
    ruby_bindir: /opt/local/bin

suites:
- name: default
  use_sudo: false
  run_list: [ 'fail2ban_smartos::default' ]
  attributes:
- name: ipfilter
  use_sudo: false
  run_list: [ 'fail2ban_smartos::ipfilter' ]
  attributes:
- name: tcp_wrapper
  use_sudo: false
  run_list: [ 'fail2ban_smartos::tcp_wrapper' ]
  attributes:

busser:
  sudo: true
